# Thanks to https://blog.knoldus.com/how-to-build-a-java-project-using-travis-ci-on-windows-platform/
#
# Not ready yet.
#
branches:
  only:
  - main

os:
  - windows

language: shell

jdk:
  - openjdk11

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
      choco install maven;
      refreshenv;
    fi;

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      #Whatever you want to do
    fi;

script:
  - export JAVA_HOME="${JAVA_HOME:-/c/jdk}"
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        maven="$(find 'C:\ProgramData\chocolatey\lib\maven' -name mvn | head -n1)";
    else
        maven="mvn";
    fi;
  - $maven
    # $maven <your_goal_here>